name: Build and deploy containerized Python app to Azure Web App - group-16-midterm

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ACR_NAME: yourAcrName            # e.g. group16acr
  IMAGE_NAME: group-16-midterm     # container repo in ACR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_200C44E8954049E5BCD12E1291E6046 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89DB40F7662A48D8B1FF52BABFE4433C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C358C471823E49D8975B84F1E67C1836 }}

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_200C44E8954049E5BCD12E1291E6046 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89DB40F7662A48D8B1FF52BABFE4433C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C358C471823E49D8975B84F1E67C1836 }}

      - name: Deploy container image to Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'group-16-midterm'
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
